-- 既存のテーブルがあれば削除（リセット用）
DROP TABLE IF EXISTS quantum_numbers;
DROP TABLE IF EXISTS chat_messages;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS profiles;

-- 1. ユーザープロフィール
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. セッション管理テーブル
CREATE TABLE sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  password TEXT NOT NULL,
  mode TEXT DEFAULT 'system',
  game_time_elapsed BIGINT DEFAULT 0,
  last_resumed_at BIGINT,
  last_updated TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. チャットメッセージ
CREATE TABLE chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES sessions(id) ON DELETE CASCADE,
  speaker_name TEXT DEFAULT '名無しさん',
  raw_text TEXT NOT NULL,
  rendered_text TEXT,
  result_json JSONB,
  type TEXT DEFAULT 'chat',
  created_at TIMESTAMPTZ DEFAULT now(),
  real_created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. 量子乱数プール
CREATE TABLE quantum_numbers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES sessions(id) ON DELETE CASCADE,
  value INTEGER NOT NULL,
  consumed BOOLEAN DEFAULT false
);

-- RLS (Row Level Security) の有効化
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE quantum_numbers ENABLE ROW LEVEL SECURITY;

-- --- ポリシー設定 ---

-- Profiles
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Sessions
CREATE POLICY "Sessions are viewable by everyone" ON sessions FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create sessions" ON sessions FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Owners can update sessions" ON sessions FOR UPDATE USING (auth.uid() = owner_id);
CREATE POLICY "Owners can delete sessions" ON sessions FOR DELETE USING (auth.uid() = owner_id);

-- Chat Messages
CREATE POLICY "Messages are viewable by everyone" ON chat_messages FOR SELECT USING (true);
CREATE POLICY "Anyone can insert messages" ON chat_messages FOR INSERT WITH CHECK (true);

-- Quantum Numbers
CREATE POLICY "Quantum numbers are viewable by everyone" ON quantum_numbers FOR SELECT USING (true);
ALTER PUBLICATION supabase_realtime ADD TABLE sessions, chat_messages;